import glob
import numpy as np
from music21 import converter, instrument, note, chord, stream
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, Activation

def get_notes():
    """ Get all the notes and chords from a small sample of Bach chorales """
    notes = []

    # Use a small number of chorales for speed
    paths = ['bach/bwv1.6.mxl', 'bach/bwv2.6.mxl']
    from music21 import corpus
    for file in paths:
        try:
            midi = corpus.parse(file)
        except:
            continue

        print("Parsing %s" % file)

        notes_to_parse = None

        try: # file has instrument parts
            s2 = instrument.partitionByInstrument(midi)
            notes_to_parse = s2.parts[0].recurse()
        except: # file has notes in a flat structure
            notes_to_parse = midi.flat.notes

        for element in notes_to_parse:
            if isinstance(element, note.Note):
                notes.append(str(element.pitch))
            elif isinstance(element, chord.Chord):
                notes.append('.'.join(str(n) for n in element.normalOrder))

    return notes

def prepare_sequences(notes, n_vocab):
    """ Prepare the sequences used by the Neural Network """
    sequence_length = 30 # short for faster training

    # get all pitch names
    pitchnames = sorted(set(item for item in notes))

    # create a dictionary to map pitches to integers
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))

    network_input = []
    network_output = []

    # create input sequences and the corresponding outputs
    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        sequence_out = notes[i + sequence_length]
        network_input.append([note_to_int[char] for char in sequence_in])
        network_output.append(note_to_int[sequence_out])

    n_patterns = len(network_input)

    # reshape the input into a format compatible with LSTM layers
    network_input = np.reshape(network_input, (n_patterns, sequence_length, 1))

    # normalize input
    network_input = network_input / float(n_vocab)

    from tensorflow.keras.utils import to_categorical
    network_output = to_categorical(network_output, num_classes=n_vocab)

    return (network_input, network_output)

def create_network(network_input, n_vocab):
    """ create the structure of the neural network """
    model = Sequential()
    model.add(LSTM(
        128,
        input_shape=(network_input.shape[1], network_input.shape[2]),
        return_sequences=False
    ))
    model.add(Dropout(0.2))
    model.add(Dense(n_vocab))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

    return model

def generate_notes(model, network_input, pitchnames, n_vocab):
    """ Generate notes from the neural network based on a sequence of notes """
    # pick a random sequence from the input as a starting point for the prediction
    start = np.random.randint(0, len(network_input)-1)

    int_to_note = dict((number, note) for number, note in enumerate(pitchnames))

    pattern = network_input[start]
    prediction_output = []

    # generate 50 notes
    for note_index in range(50):
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))

        prediction = model.predict(prediction_input, verbose=0)

        index = np.argmax(prediction)
        result = int_to_note[index]
        prediction_output.append(result)

        # pattern is a flat array, we want to append the index (unnormalized)
        pattern = np.append(pattern, index / float(n_vocab))
        pattern = pattern[1:len(pattern)]

    return prediction_output

def create_midi(prediction_output):
    """ convert the output from the prediction to notes and create a midi file
        from the notes """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp='output.mid')
    print("Saved output.mid")

def train_network():
    """ Train a Neural Network to generate music """
    print("Getting notes...")
    notes = get_notes()

    if not notes:
        print("No notes parsed. Exiting.")
        return

    n_vocab = len(set(notes))
    print(f"Notes length: {len(notes)}, vocab: {n_vocab}")

    print("Preparing sequences...")
    network_input, network_output = prepare_sequences(notes, n_vocab)

    print("Creating network...")
    model = create_network(network_input, n_vocab)

    print("Training model (10 epochs for demonstration)...")
    # Using 10 epochs and a small batch size for faster execution in this environment
    model.fit(network_input, network_output, epochs=10, batch_size=64)

    print("Generating music...")
    pitchnames = sorted(set(item for item in notes))
    # We need the unnormalized network input for generation
    # re-generating unnormalized sequences for simplicity
    sequence_length = 30
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
    unnormalized_input = []
    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        unnormalized_input.append([note_to_int[char] for char in sequence_in])
    unnormalized_input = [np.array(u) / float(n_vocab) for u in unnormalized_input] # Normalized input is used for prediction

    prediction_output = generate_notes(model, unnormalized_input, pitchnames, n_vocab)

    print("Creating MIDI...")
    create_midi(prediction_output)

if __name__ == '__main__':
    train_network()
